-- Generated by Oracle SQL Developer REST Data Services 17.2.0.188.1159
-- Exported REST Definitions from ORDS Schema Version 18.1.1.95.1251
-- Schema: ZLRECIPE   Date: Wed Aug 29 11:52:13 CST 2018
----删除已经超期的待审处方JOB
begin
  sys.dbms_scheduler.create_job(job_name            => 'ZLRECIPE.审方点评系统每日作业',
                                job_type            => 'STORED_PROCEDURE',
                                job_action          => 'ZLRECIPE.PKG_RECIPE_REVIEWE.DEL_TIMEOUT_WAIT_REVIEWE_RECIPES',
                                number_of_arguments => 1,
                                start_date          => to_date('10-07-2018 10:10:23', 'dd-mm-yyyy hh24:mi:ss'),
                                repeat_interval     => 'Freq=DAILY;ByHour=19;ByMinute=00',
                                end_date            => to_date(null),
                                job_class           => 'DEFAULT_JOB_CLASS',
                                enabled             => false,
                                auto_drop           => false,
                                comments            => '每日清除超期未审处方');
  sys.dbms_scheduler.set_job_argument_value(job_name          => 'ZLRECIPE.审方点评系统每日作业',
                                            argument_position => 1,
                                            argument_value    => '');
  sys.dbms_scheduler.enable(name => 'ZLRECIPE.审方点评系统每日作业');
end;


