--------------------------------------------------------
--  文件已创建 - 星期一-八月-13-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APEX_EXPORTS
--------------------------------------------------------

  CREATE TABLE "PATSTATUS"."APEX_EXPORTS" 
   (	"APPLICATION_ID" NUMBER, 
	"APPLICATION_NAME" VARCHAR2(255 BYTE), 
	"ALIAS" VARCHAR2(255 BYTE), 
	"EXPORT_CLOB" CLOB, 
	"EXPORT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS" 
 LOB ("EXPORT_CLOB") STORE AS SECUREFILE (
  TABLESPACE "ZL_PATIENT_STATUS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table CNDS_VS
--------------------------------------------------------

  CREATE TABLE "PATSTATUS"."CNDS_VS" 
   (	"VS_ID" VARCHAR2(36 BYTE), 
	"CNDS_TYPE" NUMBER(1,0), 
	"CNDS_VALUE" VARCHAR2(100 CHAR), 
	"VS_VALUE" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS" ;

   COMMENT ON COLUMN "PATSTATUS"."CNDS_VS"."VS_ID" IS '对照ID|';
   COMMENT ON COLUMN "PATSTATUS"."CNDS_VS"."CNDS_TYPE" IS '条件类型|1-性别条件,2-专业条件,3-年龄条件,4-婚姻条件';
   COMMENT ON COLUMN "PATSTATUS"."CNDS_VS"."CNDS_VALUE" IS '条件值|';
   COMMENT ON COLUMN "PATSTATUS"."CNDS_VS"."VS_VALUE" IS '对照值|';
   COMMENT ON TABLE "PATSTATUS"."CNDS_VS"  IS '条件对照';
--------------------------------------------------------
--  DDL for Table DICT_DEPT
--------------------------------------------------------

  CREATE TABLE "PATSTATUS"."DICT_DEPT" 
   (	"DEPT_ID" VARCHAR2(36 BYTE), 
	"DEPT_NAME" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS" ;

   COMMENT ON COLUMN "PATSTATUS"."DICT_DEPT"."DEPT_ID" IS '科室ID|';
   COMMENT ON COLUMN "PATSTATUS"."DICT_DEPT"."DEPT_NAME" IS '科室名称|';
   COMMENT ON TABLE "PATSTATUS"."DICT_DEPT"  IS '科室字典';
--------------------------------------------------------
--  DDL for Table DICT_GENDER
--------------------------------------------------------

  CREATE TABLE "PATSTATUS"."DICT_GENDER" 
   (	"GENDER_ID" VARCHAR2(36 BYTE), 
	"GENDER_NAME" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS" ;

   COMMENT ON COLUMN "PATSTATUS"."DICT_GENDER"."GENDER_ID" IS '性别ID|';
   COMMENT ON COLUMN "PATSTATUS"."DICT_GENDER"."GENDER_NAME" IS '性别名称|';
   COMMENT ON TABLE "PATSTATUS"."DICT_GENDER"  IS '性别字典';
--------------------------------------------------------
--  DDL for Table DICT_MARRIAGE
--------------------------------------------------------

  CREATE TABLE "PATSTATUS"."DICT_MARRIAGE" 
   (	"MARRIAGE_ID" VARCHAR2(36 BYTE), 
	"MARRIAGE_NAME" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS" ;

   COMMENT ON COLUMN "PATSTATUS"."DICT_MARRIAGE"."MARRIAGE_ID" IS '婚姻ID|';
   COMMENT ON COLUMN "PATSTATUS"."DICT_MARRIAGE"."MARRIAGE_NAME" IS '婚姻名称|';
   COMMENT ON TABLE "PATSTATUS"."DICT_MARRIAGE"  IS '婚姻字典';
--------------------------------------------------------
--  DDL for Table ENVR_LIST
--------------------------------------------------------

  CREATE TABLE "PATSTATUS"."ENVR_LIST" 
   (	"ENVR_ID" VARCHAR2(36 BYTE), 
	"ENVR_NAME" VARCHAR2(100 CHAR), 
	"ENVR_DESC" VARCHAR2(100 CHAR), 
	"ENABLE_SIGN" NUMBER(1,0) DEFAULT 1, 
	"LAST_MODIFIER" VARCHAR2(100 CHAR), 
	"LAST_MODIFIER_ID" VARCHAR2(36 BYTE), 
	"LAST_MODIFY_TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS" ;

   COMMENT ON COLUMN "PATSTATUS"."ENVR_LIST"."ENVR_ID" IS '场景ID|';
   COMMENT ON COLUMN "PATSTATUS"."ENVR_LIST"."ENVR_NAME" IS '场景名称|';
   COMMENT ON COLUMN "PATSTATUS"."ENVR_LIST"."ENVR_DESC" IS '场景描述|';
   COMMENT ON COLUMN "PATSTATUS"."ENVR_LIST"."ENABLE_SIGN" IS '启用标志|1-启用,0-停用;缺省=1';
   COMMENT ON COLUMN "PATSTATUS"."ENVR_LIST"."LAST_MODIFIER" IS '最后修改人|';
   COMMENT ON COLUMN "PATSTATUS"."ENVR_LIST"."LAST_MODIFIER_ID" IS '最后修改人ID|';
   COMMENT ON COLUMN "PATSTATUS"."ENVR_LIST"."LAST_MODIFY_TIME" IS '最后修改时间|';
   COMMENT ON TABLE "PATSTATUS"."ENVR_LIST"  IS '场景目录';
--------------------------------------------------------
--  DDL for Table ENVR_STATUS_VS
--------------------------------------------------------

  CREATE TABLE "PATSTATUS"."ENVR_STATUS_VS" 
   (	"ENVR_ID" VARCHAR2(36 BYTE), 
	"STATUS_ID" VARCHAR2(36 BYTE), 
	"SN" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS" ;

   COMMENT ON COLUMN "PATSTATUS"."ENVR_STATUS_VS"."ENVR_ID" IS '场景ID|';
   COMMENT ON COLUMN "PATSTATUS"."ENVR_STATUS_VS"."STATUS_ID" IS '状态ID|';
   COMMENT ON COLUMN "PATSTATUS"."ENVR_STATUS_VS"."SN" IS '序号|';
   COMMENT ON TABLE "PATSTATUS"."ENVR_STATUS_VS"  IS '场景状态对照';
--------------------------------------------------------
--  DDL for Table PARTS_LIST
--------------------------------------------------------

  CREATE TABLE "PATSTATUS"."PARTS_LIST" 
   (	"PARTS_ID" VARCHAR2(36 BYTE), 
	"PARTS_NAME" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS" ;

   COMMENT ON COLUMN "PATSTATUS"."PARTS_LIST"."PARTS_ID" IS '部位ID|';
   COMMENT ON COLUMN "PATSTATUS"."PARTS_LIST"."PARTS_NAME" IS '部位名称|';
   COMMENT ON TABLE "PATSTATUS"."PARTS_LIST"  IS '部位目录';
--------------------------------------------------------
--  DDL for Table PAT_STATUS
--------------------------------------------------------

  CREATE TABLE "PATSTATUS"."PAT_STATUS" 
   (	"PAT_STATUS_ID" VARCHAR2(36 BYTE), 
	"PID" VARCHAR2(36 BYTE), 
	"STATUS_ID" VARCHAR2(36 BYTE), 
	"STATUS_NAME" VARCHAR2(100 CHAR), 
	"STATUS_PROP" NUMBER(1,0), 
	"STATUS_SITUATION" NUMBER(1,0), 
	"STATUS_BEGIN_DATE" DATE, 
	"STATUS_END_DATE" DATE, 
	"RELATED_PARTS_ID" VARCHAR2(36 BYTE), 
	"RELATED_PARTS" VARCHAR2(100 CHAR), 
	"LAST_DETAIL_ID" VARCHAR2(36 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS" ;

   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS"."PAT_STATUS_ID" IS '病人状态ID|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS"."PID" IS '明细ID|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS"."STATUS_ID" IS '状态ID|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS"."STATUS_NAME" IS '状态名称|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS"."STATUS_PROP" IS '状态性质|1-永久状态,2-持续状态,3-限期状态';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS"."STATUS_SITUATION" IS '状态情况|1-有,2-有(复发),3-无';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS"."STATUS_BEGIN_DATE" IS '开始时间|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS"."STATUS_END_DATE" IS '解决时间|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS"."RELATED_PARTS_ID" IS '关联部位ID|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS"."RELATED_PARTS" IS '关联部位|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS"."LAST_DETAIL_ID" IS '最后明细ID|';
   COMMENT ON TABLE "PATSTATUS"."PAT_STATUS"  IS '患者状态明细';
--------------------------------------------------------
--  DDL for Table PAT_STATUS_DETAIL
--------------------------------------------------------

  CREATE TABLE "PATSTATUS"."PAT_STATUS_DETAIL" 
   (	"DETAIL_ID" VARCHAR2(36 BYTE), 
	"STATUS_ID" VARCHAR2(36 BYTE), 
	"REC_ID" VARCHAR2(36 BYTE), 
	"STATUS_NAME" VARCHAR2(100 CHAR), 
	"STATUS_PROP" NUMBER(1,0), 
	"STATUS_SITUATION" NUMBER(1,0), 
	"STATUS_BEGIN_DATE" DATE, 
	"STATUS_END_DATE" DATE, 
	"RELATED_PARTS_ID" VARCHAR2(36 BYTE), 
	"RELATED_PARTS" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS" ;

   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS_DETAIL"."DETAIL_ID" IS '明细ID|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS_DETAIL"."STATUS_ID" IS '状态ID|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS_DETAIL"."REC_ID" IS '记录ID|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS_DETAIL"."STATUS_NAME" IS '状态名称|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS_DETAIL"."STATUS_PROP" IS '状态性质|1-永久状态,2-持续状态,3-限期状态';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS_DETAIL"."STATUS_SITUATION" IS '状态情况|1-有,2-有(复发),3-无';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS_DETAIL"."STATUS_BEGIN_DATE" IS '开始时间|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS_DETAIL"."STATUS_END_DATE" IS '解决时间|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS_DETAIL"."RELATED_PARTS_ID" IS '关联部位ID|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS_DETAIL"."RELATED_PARTS" IS '关联部位|';
   COMMENT ON TABLE "PATSTATUS"."PAT_STATUS_DETAIL"  IS '患者状态明细';
--------------------------------------------------------
--  DDL for Table PAT_STATUS_REC
--------------------------------------------------------

  CREATE TABLE "PATSTATUS"."PAT_STATUS_REC" 
   (	"REC_ID" VARCHAR2(36 BYTE), 
	"PID" VARCHAR2(36 BYTE), 
	"PAT_NAME" VARCHAR2(100 CHAR), 
	"PAT_SEX" VARCHAR2(100 CHAR), 
	"BIRTH_DATE" DATE, 
	"AGE" VARCHAR2(20 CHAR), 
	"ENVR_ID" VARCHAR2(36 BYTE), 
	"VISIT_TYPE" NUMBER(1,0), 
	"PVID" VARCHAR2(36 BYTE), 
	"VISIT_TIME" DATE, 
	"VISIT_IDENTIFIER" VARCHAR2(20 CHAR), 
	"MARRY_CNDS" VARCHAR2(20 CHAR), 
	"VISIT_DEPT" VARCHAR2(100 CHAR), 
	"VISIT_DOC" VARCHAR2(100 CHAR), 
	"REC_TIME" DATE, 
	"RECORDER_ID" VARCHAR2(36 BYTE), 
	"RECORDER" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS" ;

   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS_REC"."REC_ID" IS '记录ID|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS_REC"."PID" IS '病人ID|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS_REC"."PAT_NAME" IS '姓名|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS_REC"."PAT_SEX" IS '性别|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS_REC"."BIRTH_DATE" IS '出生日期|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS_REC"."AGE" IS '年龄|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS_REC"."ENVR_ID" IS '场景ID|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS_REC"."VISIT_TYPE" IS '就诊类型|1-门诊,2-住院';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS_REC"."PVID" IS '就诊ID|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS_REC"."VISIT_TIME" IS '就诊时间|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS_REC"."VISIT_IDENTIFIER" IS '就诊标识|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS_REC"."MARRY_CNDS" IS '婚姻状态';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS_REC"."VISIT_DEPT" IS '就诊科室|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS_REC"."VISIT_DOC" IS '就诊医生|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS_REC"."REC_TIME" IS '记录时间|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS_REC"."RECORDER_ID" IS '记录人ID|';
   COMMENT ON COLUMN "PATSTATUS"."PAT_STATUS_REC"."RECORDER" IS '记录人|';
   COMMENT ON TABLE "PATSTATUS"."PAT_STATUS_REC"  IS '患者状态记录';
--------------------------------------------------------
--  DDL for Table REJECT_STATUS
--------------------------------------------------------

  CREATE TABLE "PATSTATUS"."REJECT_STATUS" 
   (	"STATUS_ID" VARCHAR2(36 BYTE), 
	"REJECT_STATUS_ID" VARCHAR2(36 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "ZL_PATIENT_STATUS" ;

   COMMENT ON COLUMN "PATSTATUS"."REJECT_STATUS"."STATUS_ID" IS '状态ID|';
   COMMENT ON COLUMN "PATSTATUS"."REJECT_STATUS"."REJECT_STATUS_ID" IS '互斥状态ID|';
   COMMENT ON TABLE "PATSTATUS"."REJECT_STATUS"  IS '互斥状态';
--------------------------------------------------------
--  DDL for Table STATUS_CNDS
--------------------------------------------------------

  CREATE TABLE "PATSTATUS"."STATUS_CNDS" 
   (	"CNDS_ID" VARCHAR2(36 BYTE), 
	"STATUS_ID" VARCHAR2(36 BYTE), 
	"CNDS_TYPE" NUMBER(1,0), 
	"CNDS_VALUE" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS" ;

   COMMENT ON COLUMN "PATSTATUS"."STATUS_CNDS"."CNDS_ID" IS '条件ID|';
   COMMENT ON COLUMN "PATSTATUS"."STATUS_CNDS"."STATUS_ID" IS '状态ID|';
   COMMENT ON COLUMN "PATSTATUS"."STATUS_CNDS"."CNDS_TYPE" IS '条件类型|1-性别条件,2-专业条件,3-年龄条件,4-婚姻条件';
   COMMENT ON COLUMN "PATSTATUS"."STATUS_CNDS"."CNDS_VALUE" IS '条件值|';
   COMMENT ON TABLE "PATSTATUS"."STATUS_CNDS"  IS '状态条件';
--------------------------------------------------------
--  DDL for Table STATUS_LIST
--------------------------------------------------------

  CREATE TABLE "PATSTATUS"."STATUS_LIST" 
   (	"STATUS_ID" VARCHAR2(36 BYTE), 
	"TYPE_ID" VARCHAR2(36 BYTE), 
	"STATUS_NAME" VARCHAR2(100 CHAR), 
	"ENABLE_SIGN" NUMBER(1,0) DEFAULT 1, 
	"STATUS_PROP" NUMBER(1,0), 
	"STDD_ID" VARCHAR2(36 BYTE), 
	"LAST_MODIFIER" VARCHAR2(100 CHAR), 
	"LAST_MODIFIER_ID" VARCHAR2(36 BYTE), 
	"LAST_MODIFY_TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS" ;

   COMMENT ON COLUMN "PATSTATUS"."STATUS_LIST"."STATUS_ID" IS '状态ID|';
   COMMENT ON COLUMN "PATSTATUS"."STATUS_LIST"."TYPE_ID" IS '类型ID|';
   COMMENT ON COLUMN "PATSTATUS"."STATUS_LIST"."STATUS_NAME" IS '状态名称|';
   COMMENT ON COLUMN "PATSTATUS"."STATUS_LIST"."ENABLE_SIGN" IS '启用标志|0-停用,1-启用;缺省=1';
   COMMENT ON COLUMN "PATSTATUS"."STATUS_LIST"."STATUS_PROP" IS '状态性质|1-永久状态,2-持续状态,3-限期状态';
   COMMENT ON COLUMN "PATSTATUS"."STATUS_LIST"."STDD_ID" IS '标准ID|';
   COMMENT ON COLUMN "PATSTATUS"."STATUS_LIST"."LAST_MODIFIER" IS '最后修改人|';
   COMMENT ON COLUMN "PATSTATUS"."STATUS_LIST"."LAST_MODIFIER_ID" IS '最后修改人ID|';
   COMMENT ON COLUMN "PATSTATUS"."STATUS_LIST"."LAST_MODIFY_TIME" IS '最后修改时间|';
   COMMENT ON TABLE "PATSTATUS"."STATUS_LIST"  IS '状态目录';
--------------------------------------------------------
--  DDL for Table STATUS_PARTS_VS
--------------------------------------------------------

  CREATE TABLE "PATSTATUS"."STATUS_PARTS_VS" 
   (	"STATUS_ID" VARCHAR2(36 BYTE), 
	"PARTS_ID" VARCHAR2(36 BYTE), 
	"DEFAULT_SIGN" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS" ;

   COMMENT ON COLUMN "PATSTATUS"."STATUS_PARTS_VS"."STATUS_ID" IS '状态ID|';
   COMMENT ON COLUMN "PATSTATUS"."STATUS_PARTS_VS"."PARTS_ID" IS '部位ID|';
   COMMENT ON COLUMN "PATSTATUS"."STATUS_PARTS_VS"."DEFAULT_SIGN" IS '默认标志|0-非默认,1-默认;缺省=0';
   COMMENT ON TABLE "PATSTATUS"."STATUS_PARTS_VS"  IS '状态部位关联';
--------------------------------------------------------
--  DDL for Table STATUS_RELATION
--------------------------------------------------------

  CREATE TABLE "PATSTATUS"."STATUS_RELATION" 
   (	"STATUS_ID" VARCHAR2(36 BYTE), 
	"PARENT_STATUS_ID" VARCHAR2(36 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "ZL_PATIENT_STATUS" ;

   COMMENT ON COLUMN "PATSTATUS"."STATUS_RELATION"."STATUS_ID" IS '状态ID|';
   COMMENT ON COLUMN "PATSTATUS"."STATUS_RELATION"."PARENT_STATUS_ID" IS '上级状态ID|';
   COMMENT ON TABLE "PATSTATUS"."STATUS_RELATION"  IS '状态关系';
--------------------------------------------------------
--  DDL for Table STATUS_TYPE
--------------------------------------------------------

  CREATE TABLE "PATSTATUS"."STATUS_TYPE" 
   (	"TYPE_ID" VARCHAR2(36 BYTE), 
	"TYPE_NAME" VARCHAR2(100 CHAR), 
	"LAST_MODIFIER" VARCHAR2(100 CHAR), 
	"LAST_MODIFIER_ID" VARCHAR2(36 BYTE), 
	"LAST_MODIFY_TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS" ;

   COMMENT ON COLUMN "PATSTATUS"."STATUS_TYPE"."TYPE_ID" IS '类型ID|';
   COMMENT ON COLUMN "PATSTATUS"."STATUS_TYPE"."TYPE_NAME" IS '类型名称|';
   COMMENT ON COLUMN "PATSTATUS"."STATUS_TYPE"."LAST_MODIFIER" IS '最后修改人|';
   COMMENT ON COLUMN "PATSTATUS"."STATUS_TYPE"."LAST_MODIFIER_ID" IS '最后修改人ID|';
   COMMENT ON COLUMN "PATSTATUS"."STATUS_TYPE"."LAST_MODIFY_TIME" IS '最后修改时间|';
   COMMENT ON TABLE "PATSTATUS"."STATUS_TYPE"  IS '状态类型';
--------------------------------------------------------
--  DDL for Index PK_STATUS_LIST
--------------------------------------------------------

  CREATE UNIQUE INDEX "PATSTATUS"."PK_STATUS_LIST" ON "PATSTATUS"."STATUS_LIST" ("STATUS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS" ;
--------------------------------------------------------
--  DDL for Index PK_PAT_STATUS_REC
--------------------------------------------------------

  CREATE UNIQUE INDEX "PATSTATUS"."PK_PAT_STATUS_REC" ON "PATSTATUS"."PAT_STATUS_REC" ("REC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS" ;
--------------------------------------------------------
--  DDL for Index PK_PARTS_LIST
--------------------------------------------------------

  CREATE UNIQUE INDEX "PATSTATUS"."PK_PARTS_LIST" ON "PATSTATUS"."PARTS_LIST" ("PARTS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS" ;
--------------------------------------------------------
--  DDL for Index PK_ENVR_LIST
--------------------------------------------------------

  CREATE UNIQUE INDEX "PATSTATUS"."PK_ENVR_LIST" ON "PATSTATUS"."ENVR_LIST" ("ENVR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS" ;
--------------------------------------------------------
--  DDL for Index PAT_STATUS_IX_STATUS_ID
--------------------------------------------------------

  CREATE INDEX "PATSTATUS"."PAT_STATUS_IX_STATUS_ID" ON "PATSTATUS"."PAT_STATUS" ("STATUS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS" ;
--------------------------------------------------------
--  DDL for Index PK_STATUS_REC_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PATSTATUS"."PK_STATUS_REC_DETAIL" ON "PATSTATUS"."PAT_STATUS_DETAIL" ("DETAIL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS" ;
--------------------------------------------------------
--  DDL for Index PK_STATUS_TYPE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PATSTATUS"."PK_STATUS_TYPE" ON "PATSTATUS"."STATUS_TYPE" ("TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS" ;
--------------------------------------------------------
--  DDL for Index IX_REC_PAT_ID
--------------------------------------------------------

  CREATE INDEX "PATSTATUS"."IX_REC_PAT_ID" ON "PATSTATUS"."PAT_STATUS_REC" ("PID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS_IX" ;
--------------------------------------------------------
--  DDL for Index PAT_STATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PATSTATUS"."PAT_STATUS_PK" ON "PATSTATUS"."PAT_STATUS" ("PAT_STATUS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS" ;
--------------------------------------------------------
--  Constraints for Table PARTS_LIST
--------------------------------------------------------

  ALTER TABLE "PATSTATUS"."PARTS_LIST" ADD CONSTRAINT "PK_PARTS_LIST" PRIMARY KEY ("PARTS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS"  ENABLE;
  ALTER TABLE "PATSTATUS"."PARTS_LIST" MODIFY ("PARTS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENVR_LIST
--------------------------------------------------------

  ALTER TABLE "PATSTATUS"."ENVR_LIST" ADD CONSTRAINT "ENVR_LIST_NN_ENABLE_SIGN" CHECK ("ENABLE_SIGN" IS NOT NULL) ENABLE;
  ALTER TABLE "PATSTATUS"."ENVR_LIST" ADD CONSTRAINT "PK_ENVR_LIST" PRIMARY KEY ("ENVR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS"  ENABLE;
  ALTER TABLE "PATSTATUS"."ENVR_LIST" MODIFY ("ENVR_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STATUS_LIST
--------------------------------------------------------

  ALTER TABLE "PATSTATUS"."STATUS_LIST" ADD CONSTRAINT "STATUS_LIST_ENABLE_SIGN" CHECK ("ENABLE_SIGN" IS NOT NULL) ENABLE;
  ALTER TABLE "PATSTATUS"."STATUS_LIST" ADD CONSTRAINT "PK_STATUS_LIST" PRIMARY KEY ("STATUS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS"  ENABLE;
  ALTER TABLE "PATSTATUS"."STATUS_LIST" MODIFY ("STATUS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DICT_GENDER
--------------------------------------------------------

  ALTER TABLE "PATSTATUS"."DICT_GENDER" MODIFY ("GENDER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAT_STATUS_REC
--------------------------------------------------------

  ALTER TABLE "PATSTATUS"."PAT_STATUS_REC" ADD CONSTRAINT "PK_PAT_STATUS_REC" PRIMARY KEY ("REC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS"  ENABLE;
  ALTER TABLE "PATSTATUS"."PAT_STATUS_REC" MODIFY ("REC_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STATUS_PARTS_VS
--------------------------------------------------------

  ALTER TABLE "PATSTATUS"."STATUS_PARTS_VS" ADD CONSTRAINT "STATUS_PART_VS_NN_DEFAULT_SIGN" CHECK ("DEFAULT_SIGN" IS NOT NULL) ENABLE;
  ALTER TABLE "PATSTATUS"."STATUS_PARTS_VS" MODIFY ("STATUS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STATUS_TYPE
--------------------------------------------------------

  ALTER TABLE "PATSTATUS"."STATUS_TYPE" ADD CONSTRAINT "PK_STATUS_TYPE" PRIMARY KEY ("TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS"  ENABLE;
  ALTER TABLE "PATSTATUS"."STATUS_TYPE" MODIFY ("TYPE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CNDS_VS
--------------------------------------------------------

  ALTER TABLE "PATSTATUS"."CNDS_VS" MODIFY ("VS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAT_STATUS_DETAIL
--------------------------------------------------------

  ALTER TABLE "PATSTATUS"."PAT_STATUS_DETAIL" ADD CONSTRAINT "PK_STATUS_REC_DETAIL" PRIMARY KEY ("DETAIL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS"  ENABLE;
  ALTER TABLE "PATSTATUS"."PAT_STATUS_DETAIL" MODIFY ("DETAIL_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REJECT_STATUS
--------------------------------------------------------

  ALTER TABLE "PATSTATUS"."REJECT_STATUS" MODIFY ("REJECT_STATUS_ID" NOT NULL ENABLE);
  ALTER TABLE "PATSTATUS"."REJECT_STATUS" MODIFY ("STATUS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAT_STATUS
--------------------------------------------------------

  ALTER TABLE "PATSTATUS"."PAT_STATUS" ADD CONSTRAINT "PAT_STATUS_PK" PRIMARY KEY ("PAT_STATUS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZL_PATIENT_STATUS"  ENABLE;
  ALTER TABLE "PATSTATUS"."PAT_STATUS" MODIFY ("PAT_STATUS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DICT_DEPT
--------------------------------------------------------

  ALTER TABLE "PATSTATUS"."DICT_DEPT" MODIFY ("DEPT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STATUS_RELATION
--------------------------------------------------------

  ALTER TABLE "PATSTATUS"."STATUS_RELATION" MODIFY ("PARENT_STATUS_ID" NOT NULL ENABLE);
  ALTER TABLE "PATSTATUS"."STATUS_RELATION" MODIFY ("STATUS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STATUS_CNDS
--------------------------------------------------------

  ALTER TABLE "PATSTATUS"."STATUS_CNDS" MODIFY ("CNDS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DICT_MARRIAGE
--------------------------------------------------------

  ALTER TABLE "PATSTATUS"."DICT_MARRIAGE" MODIFY ("MARRIAGE_ID" NOT NULL ENABLE);
