--------------------------------------------------------
--  文件已创建 - 星期四-八月-30-2018   
--------------------------------------------------------
REM INSERTING into PATSTATUS.DICT_DEPT
SET DEFINE OFF;
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191914','普外科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191915','小儿外科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191916','老年护理部');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191917','胃肠外科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191918','临床药理学系');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191919','组织病理科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191920','核医学科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191921','神经内科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191922','胸内科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191923','糖尿病科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191924','放疗科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191925','Delivery suite');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191926','肝胆外科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191927','普通口腔外科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191928','口腔正畸科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191929','职业保健科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191930','儿科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191931','普通内科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191932','口腔外科（子）');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191934','心内科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191935','妇产科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191937','小儿牙科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191938','康复精神科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191939','理疗科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191941','呼吸内科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191942','胰腺外科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191943','内科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191944','Newborn nursery unit');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191945','产科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191946','诊断影像科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191947','急诊科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191950','胸外科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191951','神经病理科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191952','移植外科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191953','分娩科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191955','眼科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191956','神经外科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191957','精神科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191959','心胸外科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191960','骨科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191961','心脏外科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191962','康复科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191963','小儿内科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191964','医学眼科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191965','耳鼻喉科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191966','整形外科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191967','老年精神科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191968','热带医学系');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191969','口腔修复科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191970','肾脏内科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191971','风湿科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191973','血管外科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191974','胸内科（子）');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191975','麻醉科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191976','眼科急诊室');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191977','内分泌科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191978','病理科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191979','临床生理学系');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191981','普通病理科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191982','输血科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191983','透析区');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191984','口腔外科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191985','外科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191986','疼痛科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191987','Young disabled unit');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191988','临床神经生理学系');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191989','临床免疫学系');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191990','内分泌外科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191991','泌尿生殖医学科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191992','泌尿科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191993','Audiology department');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191994','创伤外科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191995','妇科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191996','儿科急诊室');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191997','消化科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191998','乳腺外科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1191999','放射科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1192000','小儿肿瘤科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1192001','小儿神经内科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1192002','遗传学系');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1192004','X-ray department');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1192007','感染科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1192008','皮肤科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1192009','临床肿瘤科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1192010','手外科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1192011','血液科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1192012','临床科室');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1192013','儿童和青少年精神科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1205841','艾滋病科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1209036','整形烧伤外科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1218700','口腔科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1223074','中医科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1230683','新生儿科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1232959','痔疮科');
Insert into PATSTATUS.DICT_DEPT (DEPT_ID,DEPT_NAME) values ('1239401','介入血管外科');
