--------------------------------------------------------
--  文件已创建 - 星期三-八月-29-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REVIEWE_SOLUTION_DETAIL
--------------------------------------------------------

  CREATE TABLE "ZLRECIPE"."REVIEWE_SOLUTION_DETAIL" 
   (	"REVIEWE_SOLUTION_ID" VARCHAR2(36 CHAR), 
	"LAST_EDITOR" VARCHAR2(80 CHAR), 
	"LAST_EDIT_TIME" DATE, 
	"SOLUTION_ITEM" VARCHAR2(80 CHAR), 
	"ITEM_FIELD_NAME" VARCHAR2(80 CHAR), 
	"ITEM_EXPRESSION" VARCHAR2(20 BYTE), 
	"ITEM_VALUE" VARCHAR2(100 CHAR), 
	"ITEM_TYPE" VARCHAR2(10 CHAR), 
	"ITEM_TABLE_NAME" VARCHAR2(80 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZLR_REVIEWE" ;

   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_SOLUTION_DETAIL"."REVIEWE_SOLUTION_ID" IS '审核方案id|guid';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_SOLUTION_DETAIL"."LAST_EDITOR" IS '最后编辑者|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_SOLUTION_DETAIL"."LAST_EDIT_TIME" IS '最后编辑时间|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_SOLUTION_DETAIL"."SOLUTION_ITEM" IS '方案项目|字段显示名称';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_SOLUTION_DETAIL"."ITEM_FIELD_NAME" IS '项目字段名称|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_SOLUTION_DETAIL"."ITEM_EXPRESSION" IS '项目表达式|比如，>;<;=;包含关键字等等';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_SOLUTION_DETAIL"."ITEM_VALUE" IS '项目的值|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_SOLUTION_DETAIL"."ITEM_TYPE" IS '项目类型|处方;病人;体征';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_SOLUTION_DETAIL"."ITEM_TABLE_NAME" IS '项目对应的表名称|处方--reviewe_recipes;病人:recipe_patient_info;体征:out_patient_vital_signs';
   COMMENT ON TABLE "ZLRECIPE"."REVIEWE_SOLUTION_DETAIL"  IS '审核处方提取方案明细';
--------------------------------------------------------
--  DDL for Table REVIEWE_SOLUTION
--------------------------------------------------------

  CREATE TABLE "ZLRECIPE"."REVIEWE_SOLUTION" 
   (	"REVIEWE_SOLUTION_ID" VARCHAR2(36 BYTE), 
	"REVIEWE_SOLUTION_NAME" VARCHAR2(100 CHAR), 
	"LAST_EDITOR" VARCHAR2(80 CHAR), 
	"LAST_EDIT_TIME" DATE, 
	"REVIEWE_SOLUTION_TYPE" NUMBER, 
	"REVIEWE_SOLUTION_STATUS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZLR_REVIEWE" ;

   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_SOLUTION"."REVIEWE_SOLUTION_ID" IS '审核方案id|guid';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_SOLUTION"."REVIEWE_SOLUTION_NAME" IS '方案名称|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_SOLUTION"."LAST_EDITOR" IS '最后编辑者';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_SOLUTION"."LAST_EDIT_TIME" IS '最后编辑时间';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_SOLUTION"."REVIEWE_SOLUTION_TYPE" IS '方案类型|1-门诊;2-住院。';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_SOLUTION"."REVIEWE_SOLUTION_STATUS" IS '当前状态|1-在用;-1停用';
   COMMENT ON TABLE "ZLRECIPE"."REVIEWE_SOLUTION"  IS '审核处方提取方案';
--------------------------------------------------------
--  DDL for Table COMMENT_ITEM
--------------------------------------------------------

  CREATE TABLE "ZLRECIPE"."COMMENT_ITEM" 
   (	"ITEM_CODE" VARCHAR2(10 BYTE), 
	"ITEM_CONTENT" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZLR_REVIEWE" ;

   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_ITEM"."ITEM_CODE" IS '项目编码|';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_ITEM"."ITEM_CONTENT" IS '项目内容|';
--------------------------------------------------------
--  DDL for Table RECIPE_REVIEWE_PARA
--------------------------------------------------------

  CREATE TABLE "ZLRECIPE"."RECIPE_REVIEWE_PARA" 
   (	"PARA_NAME" VARCHAR2(100 CHAR), 
	"PARA_VALUE" VARCHAR2(500 CHAR), 
	"LAST_EDITOR" VARCHAR2(80 CHAR), 
	"LAST_EDIT_ITME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZLR_REVIEWE" ;

   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_REVIEWE_PARA"."PARA_NAME" IS '参数名称|';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_REVIEWE_PARA"."PARA_VALUE" IS '参数值|';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_REVIEWE_PARA"."LAST_EDITOR" IS '最后编辑者|';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_REVIEWE_PARA"."LAST_EDIT_ITME" IS '最后编辑时间|';
   COMMENT ON TABLE "ZLRECIPE"."RECIPE_REVIEWE_PARA"  IS '处方审核参数';
--------------------------------------------------------
--  DDL for Table RECIPE_USER
--------------------------------------------------------

  CREATE TABLE "ZLRECIPE"."RECIPE_USER" 
   (	"USER_CODE" VARCHAR2(80 BYTE), 
	"USER_NAME" VARCHAR2(36 CHAR), 
	"REGISTER_TIME" DATE, 
	"LAST_EDITOR" VARCHAR2(80 CHAR), 
	"LAST_EDIT_TIME" DATE, 
	"USER_JOB" VARCHAR2(50 CHAR), 
	"USER_STATUS" NUMBER, 
	"IS_ADMIN" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZLR_REVIEWE" ;

   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_USER"."USER_CODE" IS '用户编码|';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_USER"."USER_NAME" IS '用户姓名|';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_USER"."REGISTER_TIME" IS '用户建档时间|';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_USER"."LAST_EDITOR" IS '最后编辑者|';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_USER"."LAST_EDIT_TIME" IS '最后编辑时间|';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_USER"."USER_JOB" IS '用户岗位|药师|';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_USER"."USER_STATUS" IS '用户状态|1-启用 0-停止';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_USER"."IS_ADMIN" IS '是否系统管理员|';
   COMMENT ON TABLE "ZLRECIPE"."RECIPE_USER"  IS '审方、处方点评的用户';
--------------------------------------------------------
--  DDL for Table COMMENT_EXTRACT
--------------------------------------------------------

  CREATE TABLE "ZLRECIPE"."COMMENT_EXTRACT" 
   (	"EXTRACT_ID" NUMBER, 
	"EXTRACT_TIME" DATE, 
	"PHARMACIST" VARCHAR2(80 CHAR), 
	"PHARMACIST_ID" VARCHAR2(36 BYTE), 
	"EXTRACT_MONTH" VARCHAR2(10 BYTE), 
	"RECIPES_NUMBER" NUMBER, 
	"PATIENT_TYPE" NUMBER, 
	"SURGERY" NUMBER, 
	"RECIPE_TYPE" NUMBER, 
	"EXTRACT_TYPE" NUMBER, 
	"EXTRACT_STATUS" NUMBER DEFAULT 0, 
	"EXTRACT_DEPT_ID" VARCHAR2(36 BYTE), 
	"EXTRACT_DR_ID" VARCHAR2(36 BYTE), 
	"EXTRACT_DRUG_ID" NUMBER, 
	"EXTRACT_DRUG_NAME" VARCHAR2(80 CHAR), 
	"EXTRACT_DR_NAME" VARCHAR2(36 BYTE), 
	"EXTRACT_DEPT_NAME" VARCHAR2(80 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZLR_REVIEWE" ;

   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_EXTRACT"."EXTRACT_ID" IS '抽取ID|';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_EXTRACT"."EXTRACT_TIME" IS '抽取时间|';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_EXTRACT"."PHARMACIST" IS '点评药师|抽取者';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_EXTRACT"."PHARMACIST_ID" IS '点评药师ID|';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_EXTRACT"."EXTRACT_MONTH" IS '抽取月份|不是点评月份，而且抽取处方月份';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_EXTRACT"."RECIPES_NUMBER" IS '抽取处方数量|';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_EXTRACT"."PATIENT_TYPE" IS '病人类型|1-门诊；2-住院';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_EXTRACT"."SURGERY" IS '手术病例|0-所有病例;1-手术病例';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_EXTRACT"."RECIPE_TYPE" IS '处方类型|0-所有处方,1-预防用抗菌药物处方,2-治疗用抗菌药物处方';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_EXTRACT"."EXTRACT_TYPE" IS '提取类型|0-随机';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_EXTRACT"."EXTRACT_STATUS" IS '抽取状态|0-未完成点评,1-完成点评';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_EXTRACT"."EXTRACT_DEPT_ID" IS '抽取科室|';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_EXTRACT"."EXTRACT_DR_ID" IS '抽取医生|ZLHIS用医生的"姓名"，新门诊医生的guid';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_EXTRACT"."EXTRACT_DRUG_ID" IS '抽取药品ID|';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_EXTRACT"."EXTRACT_DRUG_NAME" IS '抽取药品名称|';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_EXTRACT"."EXTRACT_DR_NAME" IS '抽取医生|ZLHIS用医生的"别名"，新门诊医生的姓名';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_EXTRACT"."EXTRACT_DEPT_NAME" IS '抽取科室名称|';
--------------------------------------------------------
--  DDL for Table COMMENT_RECIPES
--------------------------------------------------------

  CREATE TABLE "ZLRECIPE"."COMMENT_RECIPES" 
   (	"EXTRACT_ID" NUMBER(18,0), 
	"RECIPE_NO" VARCHAR2(100 BYTE), 
	"PID" NUMBER(18,0), 
	"PVID" VARCHAR2(100 BYTE), 
	"RECIPE_DR" VARCHAR2(80 CHAR), 
	"RECIPE_DR_TITLE" VARCHAR2(20 CHAR), 
	"DR_ANTI_LEVEL" NUMBER(1,0), 
	"HIS_NO" NUMBER(18,0) DEFAULT 100, 
	"COMMENT_RESULT" NUMBER(2,0) DEFAULT 0, 
	"RECIPE_DRUG_NUMBER" NUMBER(18,0), 
	"ANTI_DRUG_MAX_LEVEL" NUMBER(18,0), 
	"RECIPE_TYPE" NUMBER(18,0), 
	"RECIPE_AMOUNT" NUMBER(18,0), 
	"PATIENT_AGE" VARCHAR2(20 BYTE), 
	"RECIPE_DIAG" VARCHAR2(4000 BYTE), 
	"BASE_DRUG_NUMBER" NUMBER(18,0), 
	"PATIENT_BIRTHDAY" DATE, 
	"RECIPE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZLR_REVIEWE" ;

   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_RECIPES"."EXTRACT_ID" IS '提取ID|';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_RECIPES"."RECIPE_NO" IS '处方号|门诊=发送.NO;住院=病人iD-主页ID';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_RECIPES"."PID" IS '病人ID|';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_RECIPES"."PVID" IS '就诊ID|';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_RECIPES"."RECIPE_DR" IS '处方医生|门诊开嘱医生;住院--住院医师';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_RECIPES"."RECIPE_DR_TITLE" IS '医生职称|';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_RECIPES"."DR_ANTI_LEVEL" IS '医生抗菌药物等级|';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_RECIPES"."HIS_NO" IS 'HIS系统号|ZLHIS固定=100';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_RECIPES"."COMMENT_RESULT" IS '点评结果|0-待点评;1-无问题;-1-有问题;';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_RECIPES"."RECIPE_DRUG_NUMBER" IS '处方药品数量|';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_RECIPES"."ANTI_DRUG_MAX_LEVEL" IS '抗菌药物最大等级|处方中抗菌药物最大等级';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_RECIPES"."RECIPE_TYPE" IS '处方类型|1-饮片处方,3-非饮片处方,4-混合处方';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_RECIPES"."RECIPE_AMOUNT" IS '处方总金额|';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_RECIPES"."PATIENT_AGE" IS '患者年龄|';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_RECIPES"."RECIPE_DIAG" IS '处方诊断|';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_RECIPES"."BASE_DRUG_NUMBER" IS '处方国家基药品种数|';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_RECIPES"."PATIENT_BIRTHDAY" IS '病人出生日期|';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_RECIPES"."RECIPE_DATE" IS '处方开具日期|门诊是处方开具日期，住院是入院日期。';
   COMMENT ON TABLE "ZLRECIPE"."COMMENT_RECIPES"  IS '提取的门诊、住院的医嘱记录';
--------------------------------------------------------
--  DDL for Table COMMENT_RESULT
--------------------------------------------------------

  CREATE TABLE "ZLRECIPE"."COMMENT_RESULT" 
   (	"RECIPE_NO" VARCHAR2(100 BYTE), 
	"COMMENT_ITEM_CODE" VARCHAR2(20 BYTE), 
	"ORDER_ID" NUMBER(18,0), 
	"COMMENT_CONTENT" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZLR_REVIEWE" ;

   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_RESULT"."RECIPE_NO" IS '处方号|门诊=发送NO；住院=病人ID-主页ID';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_RESULT"."COMMENT_ITEM_CODE" IS '点评问题项目编码|';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_RESULT"."ORDER_ID" IS '处方医嘱ID|';
   COMMENT ON COLUMN "ZLRECIPE"."COMMENT_RESULT"."COMMENT_CONTENT" IS '点评内容|';
--------------------------------------------------------
--  DDL for Table PHARMACIST_REVIEWE_DEPT
--------------------------------------------------------

  CREATE TABLE "ZLRECIPE"."PHARMACIST_REVIEWE_DEPT" 
   (	"USER_CODE" VARCHAR2(36 CHAR), 
	"DEPT_ID" VARCHAR2(36 BYTE), 
	"DEPT_NAME" VARCHAR2(80 CHAR), 
	"LAST_EDITOR" VARCHAR2(80 CHAR), 
	"LAST_EDIT_TIME" DATE, 
	"RELATION_STATUS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZLR_REVIEWE" ;

   COMMENT ON COLUMN "ZLRECIPE"."PHARMACIST_REVIEWE_DEPT"."USER_CODE" IS '用户编码|';
   COMMENT ON COLUMN "ZLRECIPE"."PHARMACIST_REVIEWE_DEPT"."DEPT_ID" IS '科室id|';
   COMMENT ON COLUMN "ZLRECIPE"."PHARMACIST_REVIEWE_DEPT"."DEPT_NAME" IS '科室名称|';
   COMMENT ON COLUMN "ZLRECIPE"."PHARMACIST_REVIEWE_DEPT"."LAST_EDITOR" IS '最后编辑者|';
   COMMENT ON COLUMN "ZLRECIPE"."PHARMACIST_REVIEWE_DEPT"."LAST_EDIT_TIME" IS '最后编辑时间|';
   COMMENT ON COLUMN "ZLRECIPE"."PHARMACIST_REVIEWE_DEPT"."RELATION_STATUS" IS '状态|1-启用,-1取消';
   COMMENT ON TABLE "ZLRECIPE"."PHARMACIST_REVIEWE_DEPT"  IS '药师负责科室';
--------------------------------------------------------
--  DDL for Table PHARMACIST_WORK_RECORD
--------------------------------------------------------

  CREATE TABLE "ZLRECIPE"."PHARMACIST_WORK_RECORD" 
   (	"PHARMACIST" VARCHAR2(80 CHAR), 
	"PHARMACIST_ID" VARCHAR2(36 BYTE), 
	"REGISTER_TIME" DATE, 
	"REGISTER_DATE" VARCHAR2(8 BYTE), 
	"UNREGISTER_TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZLR_REVIEWE" ;

   COMMENT ON COLUMN "ZLRECIPE"."PHARMACIST_WORK_RECORD"."PHARMACIST" IS '药师姓名|';
   COMMENT ON COLUMN "ZLRECIPE"."PHARMACIST_WORK_RECORD"."PHARMACIST_ID" IS '药师ID|';
   COMMENT ON COLUMN "ZLRECIPE"."PHARMACIST_WORK_RECORD"."REGISTER_TIME" IS '上岗时间';
   COMMENT ON COLUMN "ZLRECIPE"."PHARMACIST_WORK_RECORD"."REGISTER_DATE" IS '上岗日期|to_char(上岗时间,''yyyymmdd'')';
   COMMENT ON COLUMN "ZLRECIPE"."PHARMACIST_WORK_RECORD"."UNREGISTER_TIME" IS '下岗时间|';
   COMMENT ON TABLE "ZLRECIPE"."PHARMACIST_WORK_RECORD"  IS '药师上岗';
--------------------------------------------------------
--  DDL for Table RECIPE_PATIENT_INFO
--------------------------------------------------------

  CREATE TABLE "ZLRECIPE"."RECIPE_PATIENT_INFO" 
   (	"PID" NUMBER, 
	"PVID" NUMBER, 
	"P_NAME" VARCHAR2(80 CHAR), 
	"P_GENDER" VARCHAR2(10 CHAR), 
	"P_AGE" VARCHAR2(20 CHAR), 
	"P_BIRTHDAY" DATE, 
	"P_IN_TIME" DATE, 
	"P_PHYS" VARCHAR2(300 CHAR), 
	"P_OUT_TIME" DATE, 
	"P_MAJOR_DIAG" VARCHAR2(200 CHAR), 
	"P_OUT_NO" VARCHAR2(20 CHAR), 
	"P_IN_NO" VARCHAR2(20 BYTE), 
	"P_BED_NO" VARCHAR2(20 BYTE), 
	"P_DEPT_NAME" VARCHAR2(80 CHAR), 
	"P_DEPT_ID" VARCHAR2(36 BYTE), 
	"P_NURSING_DEPT_ID" VARCHAR2(36 BYTE), 
	"P_TYPE" NUMBER, 
	"P_NURSING_DEPT_NAME" VARCHAR2(80 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZLR_REVIEWE" ;

   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_PATIENT_INFO"."PID" IS '病人id|';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_PATIENT_INFO"."PVID" IS '就诊id|住院=主页id，门诊=挂号ID';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_PATIENT_INFO"."P_NAME" IS '病人姓名|';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_PATIENT_INFO"."P_GENDER" IS '病人性别|HIS的性别直接转换为汉字';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_PATIENT_INFO"."P_AGE" IS '年龄|挂号记录\病案主页中的年龄';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_PATIENT_INFO"."P_BIRTHDAY" IS '出生日期|病人信息中的出生日期';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_PATIENT_INFO"."P_IN_TIME" IS '入院日期|';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_PATIENT_INFO"."P_PHYS" IS '病生理情况|';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_PATIENT_INFO"."P_OUT_TIME" IS '出院日期|';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_PATIENT_INFO"."P_MAJOR_DIAG" IS '主要诊断|如果疑诊后面加一个？如果有多个诊断用|分隔';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_PATIENT_INFO"."P_OUT_NO" IS '门诊号|';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_PATIENT_INFO"."P_IN_NO" IS '住院号|';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_PATIENT_INFO"."P_BED_NO" IS '床号|';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_PATIENT_INFO"."P_DEPT_NAME" IS '就诊科室|';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_PATIENT_INFO"."P_DEPT_ID" IS '就诊科室ID|';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_PATIENT_INFO"."P_NURSING_DEPT_ID" IS '病区ID|住院病人才有';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_PATIENT_INFO"."P_TYPE" IS '病人类型|1-门诊,2-住院';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_PATIENT_INFO"."P_NURSING_DEPT_NAME" IS '病人病区名称|住院才有';
   COMMENT ON TABLE "ZLRECIPE"."RECIPE_PATIENT_INFO"  IS '处方患者基本信息';
--------------------------------------------------------
--  DDL for Table RECIPE_REVIEWE_LOG
--------------------------------------------------------

  CREATE TABLE "ZLRECIPE"."RECIPE_REVIEWE_LOG" 
   (	"LOG_TIME" DATE, 
	"LOG_TITLE" VARCHAR2(50 CHAR), 
	"LOG_TYPE" VARCHAR2(2 CHAR), 
	"LOG_CONTENT" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZLR_REVIEWE"   NO INMEMORY 
 LOB ("LOG_CONTENT") STORE AS SECUREFILE (
  TABLESPACE "ZLR_REVIEWE" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_REVIEWE_LOG"."LOG_TIME" IS '日志时间|记录数据';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_REVIEWE_LOG"."LOG_TITLE" IS '日志标题';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_REVIEWE_LOG"."LOG_TYPE" IS '日志类型|N-运行记录;A-警告;E-错误';
   COMMENT ON COLUMN "ZLRECIPE"."RECIPE_REVIEWE_LOG"."LOG_CONTENT" IS '日志详细内容|';
--------------------------------------------------------
--  DDL for Table REVIEWE_DEPT
--------------------------------------------------------

  CREATE TABLE "ZLRECIPE"."REVIEWE_DEPT" 
   (	"DEPT_ID" VARCHAR2(36 BYTE), 
	"DEPT_NAME" VARCHAR2(80 CHAR), 
	"LAST_EDITOR" VARCHAR2(80 CHAR), 
	"LAST_EDIT_TIME" DATE, 
	"DEPT_STATUS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZLR_REVIEWE" ;

   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_DEPT"."DEPT_ID" IS '科室id|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_DEPT"."DEPT_NAME" IS '科室名称|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_DEPT"."LAST_EDITOR" IS '最后编辑者';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_DEPT"."LAST_EDIT_TIME" IS '最后编辑时间';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_DEPT"."DEPT_STATUS" IS '状态|1-启用,-1取消';
   COMMENT ON TABLE "ZLRECIPE"."REVIEWE_DEPT"  IS '审方启用科室';
--------------------------------------------------------
--  DDL for Table REVIEWE_NO_PASS_REASON
--------------------------------------------------------

  CREATE TABLE "ZLRECIPE"."REVIEWE_NO_PASS_REASON" 
   (	"REASON_CONTENT" VARCHAR2(50 CHAR), 
	"REASON_CODE" VARCHAR2(20 CHAR), 
	"REASON_ID" NVARCHAR2(18)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZLR_REVIEWE" ;

   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_NO_PASS_REASON"."REASON_CONTENT" IS '原因内容|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_NO_PASS_REASON"."REASON_CODE" IS '原因编码|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_NO_PASS_REASON"."REASON_ID" IS '不通过理由ID|';
--------------------------------------------------------
--  DDL for Table REVIEWE_RECIPES
--------------------------------------------------------

  CREATE TABLE "ZLRECIPE"."REVIEWE_RECIPES" 
   (	"PID" NUMBER, 
	"PVID" NUMBER, 
	"ORDER_STAT" NUMBER, 
	"ORDER_GROUP_ID" NUMBER, 
	"ORDER_ID" NUMBER, 
	"ORDER_BABY" NUMBER, 
	"RECIPE_TIME" DATE, 
	"RECIPE_DATE" VARCHAR2(8 BYTE), 
	"EMERGENCY" NUMBER, 
	"RECIPE_DR" VARCHAR2(80 CHAR), 
	"RECIPE_DR_TITLE" VARCHAR2(20 CHAR), 
	"ORDER_COMMENT" VARCHAR2(1000 CHAR), 
	"DR_ANTI_LEVEL" NUMBER, 
	"DRUG_BASE_CODE" VARCHAR2(14 BYTE), 
	"DRUG_FORM" VARCHAR2(50 CHAR), 
	"DRUG_TIME_INTERVAL" VARCHAR2(50 CHAR), 
	"DRUG_ROUTE" VARCHAR2(100 CHAR), 
	"DRUG_ONCE_DOSEAGE" NUMBER, 
	"DRUG_DAY_DOSEAGE" NUMBER, 
	"DRUG_DOSEAGE_UNIT" VARCHAR2(50 CHAR), 
	"DRUG_USED_DAYS" NUMBER, 
	"OVER_DOSEAGE_REASON" VARCHAR2(500 CHAR), 
	"DR_CONTRA_COMMENT" VARCHAR2(1000 CHAR), 
	"DRUG_TOXICITY" VARCHAR2(50 CHAR), 
	"DRUG_ANTI_LEVEL" NUMBER, 
	"ANTI_DRUG_REASON" VARCHAR2(10 CHAR), 
	"HIS_NO" NUMBER DEFAULT 100, 
	"RECIPE_DIAG" VARCHAR2(500 CHAR), 
	"RECEIVE_TIME" DATE, 
	"RECEIVE_DATE" VARCHAR2(8 BYTE), 
	"REVIEWE_NORMAL_TIME" DATE, 
	"PHARMACIST" VARCHAR2(80 CHAR), 
	"PHARMACIST_ID" VARCHAR2(36 BYTE), 
	"REVIEWE_RESULT" NUMBER, 
	"REVIEWE_TIME" DATE, 
	"PHARMACIST_RECEIVE_TIME" DATE, 
	"REVIEWE_COMMENT" VARCHAR2(4000 BYTE), 
	"DR_REFUSE" NUMBER, 
	"DR_REFUSE_COMMENT" VARCHAR2(4000 BYTE), 
	"DR_REFUSE_TIME" DATE, 
	"DRUG_CONTRA_LEVEL" VARCHAR2(20 CHAR), 
	"DRUG_CONTRA_TYPE" VARCHAR2(200 CHAR), 
	"DRUG_CONTRA_COMMENT" VARCHAR2(1000 CHAR), 
	"DRUG_ROUTE_NAME" VARCHAR2(100 CHAR), 
	"DRUG_CONTRA_TYPE_CODE" VARCHAR2(200 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZLR_REVIEWE"   NO INMEMORY ;

   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."PID" IS '病人id|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."PVID" IS '就诊ID|门诊挂号单id,住院主页id';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."ORDER_STAT" IS '临时医嘱|1-临时，0-长期';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."ORDER_GROUP_ID" IS '输液组号|药品医嘱的相关ID';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."ORDER_ID" IS '医嘱id|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."ORDER_BABY" IS '婴儿医嘱|0-母亲;1-N：婴儿序号';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."RECIPE_TIME" IS '开嘱时间|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."RECIPE_DATE" IS '开嘱日期|to_char(开嘱时间,''yyyymmdd'')';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."EMERGENCY" IS '紧急标志|0-普通;1-紧急;2-补录';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."RECIPE_DR" IS '开嘱医生|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."RECIPE_DR_TITLE" IS '开嘱医生职称|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."ORDER_COMMENT" IS '医嘱内容|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."DR_ANTI_LEVEL" IS '开嘱医生抗菌药物等级|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."DRUG_BASE_CODE" IS '药品本位码|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."DRUG_FORM" IS '药品剂型|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."DRUG_TIME_INTERVAL" IS '给药频次|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."DRUG_ROUTE" IS '给药途径|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."DRUG_ONCE_DOSEAGE" IS '单次用量';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."DRUG_DAY_DOSEAGE" IS '单日用量|函数计算';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."DRUG_DOSEAGE_UNIT" IS '剂量单位|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."DRUG_USED_DAYS" IS '用药天数|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."OVER_DOSEAGE_REASON" IS '超量用药说明|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."DR_CONTRA_COMMENT" IS '医师使用禁忌药品说明|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."DRUG_TOXICITY" IS '毒理分类|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."DRUG_ANTI_LEVEL" IS '抗菌药物等级|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."ANTI_DRUG_REASON" IS '用药目的|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."HIS_NO" IS 'his系统|100-ZLHIS;200--新门诊';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."RECIPE_DIAG" IS '处方诊断|多个之间用|分隔';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."RECEIVE_TIME" IS '医嘱接收时间|审方系统接收到处方的时间';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."RECEIVE_DATE" IS '接收日期|接收处方的日期';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."REVIEWE_NORMAL_TIME" IS '正常完成时间|审方系统接收到处方的时间+参数配置的标准间隔时长,超过这个时间点就自动通过';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."PHARMACIST" IS '药师|审方系统用户名称';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."PHARMACIST_ID" IS '药师ID|审方系统用户ID';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."REVIEWE_RESULT" IS '审核结果|20-无需审核;21-无药师上岗自动通过;22-超时自动通过;23-未上班无需审核-2-接收未处理;0-待审;-1-未通过;1-通过,2-审核中';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."REVIEWE_TIME" IS '审方时间|药师完成审方的时间';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."PHARMACIST_RECEIVE_TIME" IS '药师接单时间|药师接收待审处方的时间';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."REVIEWE_COMMENT" IS '药师审核说明|对于未通过的药师给出理由说明';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."DR_REFUSE" IS '医师是否拒绝药师不通过审核|缺省=1-同意;-1拒绝';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."DR_REFUSE_COMMENT" IS '医师拒绝理由|医师不同意药师审核意见，说明理由继续使用';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."DR_REFUSE_TIME" IS '医师拒绝时间|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."DRUG_CONTRA_LEVEL" IS '药品禁忌等级|禁用、慎用等';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."DRUG_CONTRA_TYPE" IS '药品禁忌类型|来源于合理用药';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."DRUG_CONTRA_COMMENT" IS '药品禁忌说明|来源于合理用药';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."DRUG_ROUTE_NAME" IS '给药途径名称|';
   COMMENT ON COLUMN "ZLRECIPE"."REVIEWE_RECIPES"."DRUG_CONTRA_TYPE_CODE" IS '药品禁忌类型编码|来源于合理用药';
   COMMENT ON TABLE "ZLRECIPE"."REVIEWE_RECIPES"  IS '提取的门诊、住院的医嘱记录';
--------------------------------------------------------
--  DDL for Table WAIT_REVIEWE_RECIPE
--------------------------------------------------------

  CREATE TABLE "ZLRECIPE"."WAIT_REVIEWE_RECIPE" 
   (	"ORDER_ID" NUMBER, 
	"RECEIVE_TIME" DATE, 
	"RECEIVE_DATE" VARCHAR2(8 BYTE), 
	"REVIEWE_NORMAL_TIME" DATE, 
	"PID" NUMBER, 
	"PVID" NUMBER, 
	"P_DEPT_ID" VARCHAR2(36 BYTE), 
	"PHARMACIST" VARCHAR2(80 CHAR), 
	"PHARMACIST_ID" VARCHAR2(36 BYTE), 
	"PHARMACIST_RECEIVE_TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZLR_REVIEWE"   NO INMEMORY ;

   COMMENT ON COLUMN "ZLRECIPE"."WAIT_REVIEWE_RECIPE"."ORDER_ID" IS '医嘱id|';
   COMMENT ON COLUMN "ZLRECIPE"."WAIT_REVIEWE_RECIPE"."RECEIVE_TIME" IS '医嘱接收时间|审方系统接收到处方的时间';
   COMMENT ON COLUMN "ZLRECIPE"."WAIT_REVIEWE_RECIPE"."RECEIVE_DATE" IS '医嘱接收日期|';
   COMMENT ON COLUMN "ZLRECIPE"."WAIT_REVIEWE_RECIPE"."REVIEWE_NORMAL_TIME" IS '正常完成时间|审方系统接收到处方的时间+参数配置的标准间隔时长,超过这个时间点就自动通过';
   COMMENT ON COLUMN "ZLRECIPE"."WAIT_REVIEWE_RECIPE"."PID" IS '病人id|';
   COMMENT ON COLUMN "ZLRECIPE"."WAIT_REVIEWE_RECIPE"."PVID" IS '就诊id|住院=主页id，门诊=挂号id';
   COMMENT ON COLUMN "ZLRECIPE"."WAIT_REVIEWE_RECIPE"."P_DEPT_ID" IS '就诊科室ID|';
   COMMENT ON COLUMN "ZLRECIPE"."WAIT_REVIEWE_RECIPE"."PHARMACIST" IS '药师|非ZLHIS的用户名称';
   COMMENT ON COLUMN "ZLRECIPE"."WAIT_REVIEWE_RECIPE"."PHARMACIST_ID" IS '药师ID|新门诊是GUID';
   COMMENT ON COLUMN "ZLRECIPE"."WAIT_REVIEWE_RECIPE"."PHARMACIST_RECEIVE_TIME" IS '药师接单时间|药师接收待审处方的时间';
   COMMENT ON TABLE "ZLRECIPE"."WAIT_REVIEWE_RECIPE"  IS '待审核处方，完成审方后（包括自动完成)删除';
--------------------------------------------------------
--  DDL for Table ZLPINYIN
--------------------------------------------------------

  CREATE TABLE "ZLRECIPE"."ZLPINYIN" 
   (	"汉字" NUMBER(5,0), 
	"拼音" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZLR_REVIEWE" ;
REM INSERTING into ZLRECIPE.REVIEWE_SOLUTION_DETAIL
SET DEFINE OFF;
Insert into ZLRECIPE.REVIEWE_SOLUTION_DETAIL (REVIEWE_SOLUTION_ID,LAST_EDITOR,LAST_EDIT_TIME,SOLUTION_ITEM,ITEM_FIELD_NAME,ITEM_EXPRESSION,ITEM_VALUE,ITEM_TYPE,ITEM_TABLE_NAME) values ('6FB8771AD80DBAE1E055000000000001','吴开波',to_date('28-8月 -18','DD-MON-RR'),'禁忌等级','drug_contra_level','含有','禁用','处方','reviewe_recipes');
Insert into ZLRECIPE.REVIEWE_SOLUTION_DETAIL (REVIEWE_SOLUTION_ID,LAST_EDITOR,LAST_EDIT_TIME,SOLUTION_ITEM,ITEM_FIELD_NAME,ITEM_EXPRESSION,ITEM_VALUE,ITEM_TYPE,ITEM_TABLE_NAME) values ('7041A652BA3FCAC6E055000000000001','王冠英',to_date('15-8月 -18','DD-MON-RR'),'禁忌等级','drug_contra_level','含有','禁用','处方','reviewe_recipes');
REM INSERTING into ZLRECIPE.REVIEWE_SOLUTION
SET DEFINE OFF;
Insert into ZLRECIPE.REVIEWE_SOLUTION (REVIEWE_SOLUTION_ID,REVIEWE_SOLUTION_NAME,LAST_EDITOR,LAST_EDIT_TIME,REVIEWE_SOLUTION_TYPE,REVIEWE_SOLUTION_STATUS) values ('7041A652BA3FCAC6E055000000000001','住院方案','吴开波',to_date('28-8月 -18','DD-MON-RR'),2,1);
Insert into ZLRECIPE.REVIEWE_SOLUTION (REVIEWE_SOLUTION_ID,REVIEWE_SOLUTION_NAME,LAST_EDITOR,LAST_EDIT_TIME,REVIEWE_SOLUTION_TYPE,REVIEWE_SOLUTION_STATUS) values ('6FB8771AD80DBAE1E055000000000001','门诊方案','王冠英',to_date('16-8月 -18','DD-MON-RR'),1,1);
REM INSERTING into ZLRECIPE.COMMENT_ITEM
SET DEFINE OFF;
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('1-1','处方的前记、正文、后记内容缺项，书写不规范或者字迹难以辨认的');
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('1-2','医师签名、签章不规范或者与签名、签章的留样不一致的');
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('1-3','药师未对处方进行适宜性审核的（处方后记的审核、调配、核对、发药栏目无审核调配药师及核对发药药师签名，或者单人值班调剂未执行双签名规定）');
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('1-4','新生儿、婴幼儿处方未写明日、月龄的');
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('1-5','西药、中成药与中药饮片未分别开具处方的');
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('1-6','未使用药品规范名称开具处方的');
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('1-7','药品的剂量、规格、数量、单位等书写不规范或不清楚的');
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('1-8','用法、用量使用“遵医嘱”、“自用”等含糊不清字句的');
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('1-9','处方修改未签名并注明修改日期，或药品超剂量使用未注明原因和再次签名的');
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('1-10','开具处方未写临床诊断或临床诊断书写不全的');
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('1-11','单张门急诊处方超过五种药品的');
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('1-12','无特殊情况下，门诊处方超过7日用量，急诊处方超过3日用量，慢性病、老年病或特殊情况下需要适当延长处方用量未注明理由的');
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('1-13','开具麻醉药品、精神药品、医疗用毒性药品、放射性药品等特殊管理药品处方未执行国家有关规定的');
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('1-14','医师未按照抗菌药物临床应用管理规定开具抗菌药物处方的');
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('1-15','中药饮片处方药物未按照“君、臣、佐、使”的顺序排列，或未按要求标注药物调剂、煎煮等特殊要求的');
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('2-1','适应证不适宜的');
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('2-2','遴选的药品不适宜的；（有禁忌的用药）');
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('2-3','药品剂型或给药途径不适宜的');
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('2-4','无正当理由不首选国家基本药物的');
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('2-5','用法、用量不适宜的');
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('2-6','联合用药不适宜的');
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('2-7','重复给药的');
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('2-8','有配伍禁忌或者不良相互作用的');
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('2-9','其它用药不适宜情况的');
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('3-1','1.无适应证用药');
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('3-2','2.无正当理由开具高价药的');
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('3-3','3.无正当理由超说明书用药的');
Insert into ZLRECIPE.COMMENT_ITEM (ITEM_CODE,ITEM_CONTENT) values ('3-4','4.无正当理由为同一患者同时开具2种以上药理作用相同药物的');
REM INSERTING into ZLRECIPE.RECIPE_REVIEWE_PARA
SET DEFINE OFF;
Insert into ZLRECIPE.RECIPE_REVIEWE_PARA (PARA_NAME,PARA_VALUE,LAST_EDITOR,LAST_EDIT_ITME) values ('合理用药服务器','192.168.32.201',null,null);
Insert into ZLRECIPE.RECIPE_REVIEWE_PARA (PARA_NAME,PARA_VALUE,LAST_EDITOR,LAST_EDIT_ITME) values ('审方定时刷新间隔','10','吴开波',to_date('28-8月 -18','DD-MON-RR'));
Insert into ZLRECIPE.RECIPE_REVIEWE_PARA (PARA_NAME,PARA_VALUE,LAST_EDITOR,LAST_EDIT_ITME) values ('ZLHIS数据库','(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.9.140)(PORT=1522))(CONNECT_DATA=(SERVICE_NAME=dyey))):ZLHIS:aqa:1:',null,null);
Insert into ZLRECIPE.RECIPE_REVIEWE_PARA (PARA_NAME,PARA_VALUE,LAST_EDITOR,LAST_EDIT_ITME) values ('审方服务器地址','192.168.0.231:8080',null,null);
Insert into ZLRECIPE.RECIPE_REVIEWE_PARA (PARA_NAME,PARA_VALUE,LAST_EDITOR,LAST_EDIT_ITME) values ('上午上班时间','8:00',null,null);
Insert into ZLRECIPE.RECIPE_REVIEWE_PARA (PARA_NAME,PARA_VALUE,LAST_EDITOR,LAST_EDIT_ITME) values ('上午下班时间','12:00','吴开波',to_date('02-8月 -18','DD-MON-RR'));
Insert into ZLRECIPE.RECIPE_REVIEWE_PARA (PARA_NAME,PARA_VALUE,LAST_EDITOR,LAST_EDIT_ITME) values ('下午上班时间','12:00','吴开波',to_date('02-8月 -18','DD-MON-RR'));
Insert into ZLRECIPE.RECIPE_REVIEWE_PARA (PARA_NAME,PARA_VALUE,LAST_EDITOR,LAST_EDIT_ITME) values ('下午下班时间','22:00',null,null);
Insert into ZLRECIPE.RECIPE_REVIEWE_PARA (PARA_NAME,PARA_VALUE,LAST_EDITOR,LAST_EDIT_ITME) values ('超时自动通过间隔时长','6','吴开波',to_date('23-8月 -18','DD-MON-RR'));
REM INSERTING into ZLRECIPE.RECIPE_USER
SET DEFINE OFF;
Insert into ZLRECIPE.RECIPE_USER (USER_CODE,USER_NAME,REGISTER_TIME,LAST_EDITOR,LAST_EDIT_TIME,USER_JOB,USER_STATUS,IS_ADMIN) values ('Y0282','向玉',to_date('27-8月 -18','DD-MON-RR'),'WKB',to_date('27-8月 -18','DD-MON-RR'),'药师',1,0);
Insert into ZLRECIPE.RECIPE_USER (USER_CODE,USER_NAME,REGISTER_TIME,LAST_EDITOR,LAST_EDIT_TIME,USER_JOB,USER_STATUS,IS_ADMIN) values ('ADMIN','管理员',null,null,null,null,null,1);
Insert into ZLRECIPE.RECIPE_USER (USER_CODE,USER_NAME,REGISTER_TIME,LAST_EDITOR,LAST_EDIT_TIME,USER_JOB,USER_STATUS,IS_ADMIN) values ('LH','罗虹',to_date('06-6月 -18','DD-MON-RR'),'WKB',to_date('11-7月 -18','DD-MON-RR'),'主任药师',1,1);
Insert into ZLRECIPE.RECIPE_USER (USER_CODE,USER_NAME,REGISTER_TIME,LAST_EDITOR,LAST_EDIT_TIME,USER_JOB,USER_STATUS,IS_ADMIN) values ('BT','白天',to_date('06-6月 -18','DD-MON-RR'),'WKB',to_date('10-7月 -18','DD-MON-RR'),'副主任药师',1,1);
Insert into ZLRECIPE.RECIPE_USER (USER_CODE,USER_NAME,REGISTER_TIME,LAST_EDITOR,LAST_EDIT_TIME,USER_JOB,USER_STATUS,IS_ADMIN) values ('WKB','吴开波',to_date('06-6月 -18','DD-MON-RR'),'WKB',to_date('09-7月 -18','DD-MON-RR'),'副主任药师',1,1);
Insert into ZLRECIPE.RECIPE_USER (USER_CODE,USER_NAME,REGISTER_TIME,LAST_EDITOR,LAST_EDIT_TIME,USER_JOB,USER_STATUS,IS_ADMIN) values ('XXF','徐晓枫',to_date('26-6月 -18','DD-MON-RR'),null,null,'药师',1,0);
Insert into ZLRECIPE.RECIPE_USER (USER_CODE,USER_NAME,REGISTER_TIME,LAST_EDITOR,LAST_EDIT_TIME,USER_JOB,USER_STATUS,IS_ADMIN) values ('WGY','王冠英',to_date('26-6月 -18','DD-MON-RR'),'LH',to_date('15-8月 -18','DD-MON-RR'),'药师',1,1);
Insert into ZLRECIPE.RECIPE_USER (USER_CODE,USER_NAME,REGISTER_TIME,LAST_EDITOR,LAST_EDIT_TIME,USER_JOB,USER_STATUS,IS_ADMIN) values ('Y0266','杨奎',to_date('17-8月 -18','DD-MON-RR'),'WKB',to_date('27-8月 -18','DD-MON-RR'),'主管药师',1,0);
