--------------------------------------------------------
--  文件已创建 - 星期五-七月-13-2018
--------------------------------------------------------
REM INSERTING into ZLRECIPE.REVIEWE_SOLUTION_DETAIL
SET DEFINE OFF;
Insert into ZLRECIPE.REVIEWE_SOLUTION_DETAIL (REVIEWE_SOLUTION_ID,LAST_EDITOR,LAST_EDIT_TIME,SOLUTION_ITEM,ITEM_FIELD_NAME,ITEM_EXPRESSION,ITEM_VALUE,ITEM_TYPE,ITEM_TABLE_NAME) values ('6FB8771AD80DBAE1E055000000000001','罗虹',to_date('2018-07-13 11:23:24','RRRR-MM-DD hh24:mi:ss'),'禁忌等级','drug_contra_level','含有','禁用','处方','reviewe_recipes');
Insert into ZLRECIPE.REVIEWE_SOLUTION_DETAIL (REVIEWE_SOLUTION_ID,LAST_EDITOR,LAST_EDIT_TIME,SOLUTION_ITEM,ITEM_FIELD_NAME,ITEM_EXPRESSION,ITEM_VALUE,ITEM_TYPE,ITEM_TABLE_NAME) values ('7041A652BA3FCAC6E055000000000001','罗虹',to_date('2018-07-13 11:21:49','RRRR-MM-DD hh24:mi:ss'),'禁忌等级','drug_contra_level','含有','禁用','处方','reviewe_recipes');
